config/routes.rb
Rails.application.routes.draw do
  resources :document_state_rels
  resources :document_states
  resources :document_types
  #session
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'welcome', to: 'session#welcome'
  get 'destroy', to: 'session#destroy'
  get 'authorized', to: 'session#page_requires_login'
  #resources
  resources 'users'
  resources 'suppliers'
  resources 'documents'

  root 'session#new'
end

app/models/document_state_rel.rb
class DocumentStateRel < ApplicationRecord
  belongs_to :user
  belongs_to :document
  belongs_to :document_state
end

app/controllers/document_state_rels_controller.rb
class DocumentStateRelsController < ApplicationController
  before_action :set_document_state_rel, only: [:show, :edit, :update, :destroy]

  # GET /document_state_rels
  # GET /document_state_rels.json
  def index
    @document_state_rels = DocumentStateRel.all
  end

  # GET /document_state_rels/1
  # GET /document_state_rels/1.json
  def show
  end

  # GET /document_state_rels/new
  def new
    @document = Document.find(params[:document_id])
    @document_state_rel = DocumentStateRel.new
  end

  # GET /document_state_rels/1/edit
  def edit
  end

  # POST /document_state_rels
  # POST /document_state_rels.json
  def create
    @document_state_rel = DocumentStateRel.new(document_state_rel_params)

    respond_to do |format|
      if @document_state_rel.save
        format.html { redirect_to @document_state_rel, notice: 'Document state rel was successfully created.' }
        format.json { render :show, status: :created, location: @document_state_rel }
      else
        format.html { render :new }
        format.json { render json: @document_state_rel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_state_rels/1
  # PATCH/PUT /document_state_rels/1.json
  def update
    respond_to do |format|
      if @document_state_rel.update(document_state_rel_params)
        format.html { redirect_to @document_state_rel, notice: 'Document state rel was successfully updated.' }
        format.json { render :show, status: :ok, location: @document_state_rel }
      else
        format.html { render :edit }
        format.json { render json: @document_state_rel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_state_rels/1
  # DELETE /document_state_rels/1.json
  def destroy
    @document_state_rel.destroy
    respond_to do |format|
      format.html { redirect_to document_state_rels_url, notice: 'Document state rel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_state_rel
      @document_state_rel = DocumentStateRel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_state_rel_params
      params.require(:document_state_rel).permit(:date, :name, :description, :obs, :user_id, :document_id, :document_state_id)
    end
end

app/helpers/document_state_rels_helper.rb
module DocumentStateRelsHelper
end

app/views/document_state_rels/_form.html.erb
<%= form_for @document_state_rel do |form| %>
  <% if @document_state_rel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document_state_rel.errors.count, "error") %> prohibited this document_state_rel from being saved:</h2>

      <ul>
        <% @document_state_rel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
  <div class="form-group col-md-6">
    <%= form.label :date, "Fecha" %>
    <%= form.datetime_field :date, class: "form-control" %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  </div>

  <div class="form-row">
  <div class="form-group col-md-6">
    <%= form.label :description, "Descripcion" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :user_id, "Usuario" %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%= form.select :user_id, User.all.collect {|d| [d.name, d.id]}, { :include_blank => "Seleccione", :selected => current_user.id }, { :class => "form-control", :disabled => true } %>
  </div>
  </div>

  <div class="form-row">
  <div class="form-group col-md-6">
    <%= form.label :document_id, "Documento" %>
    <%= form.hidden_field :document_id, :value => @document.id %>
    <%= form.select :document_id, Document.all.collect {|d| [d.doc_code, d.id]}, { :include_blank => "Seleccione", :selected => @document.id }, { :class => "form-control", :disabled => true } %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :document_state_id, "Estado" %>
    <%= form.select :document_state_id, DocumentState.all.collect {|d| [d.name, d.id]}, { :include_blank => "Seleccione", disabled:true }, { :class => "form-control" } %>
  </div>
  </div>

  <div class="form-group">
    <%= form.label :obs, "Observaciones" %>
    <%= form.text_area :obs, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= form.submit "Guardar", :class => "btn btn-primary" %>
  <%= link_to "Volver", :back, :class => "btn btn-secondary" %>
  </div>
<% end %>

app/views/document_state_rels/edit.html.erb
<h1>Editing Document State Rel</h1>

<%= render 'form', document_state_rel: @document_state_rel %>

<%= link_to 'Show', @document_state_rel %> |
<%= link_to 'Back', document_state_rels_path %>

app/views/document_state_rels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Document State Rels</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Description</th>
      <th>Obs</th>
      <th>Document</th>
      <th>Document state</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @document_state_rels.each do |document_state_rel| %>
      <tr>
        <td><%= document_state_rel.date %></td>
        <td><%= document_state_rel.name %></td>
        <td><%= document_state_rel.description %></td>
        <td><%= document_state_rel.obs %></td>
        <td><%= document_state_rel.document_id %></td>
        <td><%= document_state_rel.document_state_id %></td>
        <td><%= link_to 'Show', document_state_rel %></td>
        <td><%= link_to 'Edit', edit_document_state_rel_path(document_state_rel) %></td>
        <td><%= link_to 'Destroy', document_state_rel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document State Rel', new_document_state_rel_path %>

app/views/document_state_rels/new.html.erb
<div class="content content-fixed">
      <div class="container pd-x-0 pd-lg-x-10 pd-xl-x-0">
        <div class="d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-30">
          <div>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb breadcrumb-style1 mg-b-10">
                <li class="breadcrumb-item"><a href="#">Estado de Documento</a></li>
                <li class="breadcrumb-item active" aria-current="page">Nuevo</li>
              </ol>
            </nav>
          </div>
        </div>
        <div class="row row-xs">
          <div class="col-lg-12">
            <div class="card">
              <div class="card-header d-sm-flex justify-content-between bd-b-0 pd-t-20 pd-b-0">
              </div>
              <div class="card-body">
                <%= render 'form' %>
              </div><!-- card-body -->
            </div><!-- card -->
          </div><!-- col -->
        </div><!-- row -->
      </div><!-- container -->
    </div><!-- content -->

app/views/document_state_rels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @document_state_rel.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @document_state_rel.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document_state_rel.description %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @document_state_rel.obs %>
</p>

<p>
  <strong>Document:</strong>
  <%= @document_state_rel.document_id %>
</p>

<p>
  <strong>Document state:</strong>
  <%= @document_state_rel.document_state_id %>
</p>

<%= link_to 'Edit', edit_document_state_rel_path(@document_state_rel) %> |
<%= link_to 'Back', document_state_rels_path %>